image: cypress/browsers:node18.12.0-chrome107

stages:
  - test
  - report

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

test:
  stage: test
  script:
    - npm ci
    - mkdir -p cypress/reports/.jsons
    - mkdir -p cypress/reports/html
    - npm run cypress:e2e
  artifacts:
    when: always
    paths:
      - cypress/reports/
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 1 day

report:
  stage: report
  script:
    - npm ci
    - mkdir -p cypress/reports
    - npm run report:merge
    - npm run report:generate
  artifacts:
    when: always
    paths:
      - cypress/reports/output.json
      - cypress/reports/output.html
    expire_in: 1 day
  dependencies:
    - test